# Generated by Django 5.2.15 on 2026-07-06 17:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('active', 'Active'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='active', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('last_recorded_at', models.DateTimeField(blank=True, null=True)),
                ('distance_m', models.PositiveIntegerField(default=0)),
                ('duration_s', models.PositiveIntegerField(default=0)),
                ('avg_speed_kmh', models.FloatField(default=0)),
                ('samples_count', models.PositiveIntegerField(default=0)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_sessions', to='club.userprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
